#ifndef COMMON_H
#define COMMON_H

#include <stdint.h>

// ===== CONFIGURATION =====
#define VERSION "4.0.0"
#define MAX_LINE_LENGTH 4096
#define MAX_MACROS 100
#define MAX_PACKAGES 50

// ===== TYPES DE BASE =====
typedef enum {
    VAL_NIL, VAL_BOOL, VAL_INT, VAL_FLOAT, 
    VAL_STRING, VAL_FUNCTION, VAL_NATIVE, VAL_RETURN_SIG,
    VAL_ARRAY, VAL_OBJECT, VAL_CLOSURE, VAL_GENERATOR,
    VAL_PROMISE, VAL_ERROR, VAL_REGEX, VAL_BUFFER,
    VAL_DATE, VAL_SYMBOL, VAL_BIGINT, VAL_ITERATOR,
    VAL_BREAK, VAL_CONTINUE
} ValueType;

// ===== LEXER =====
typedef enum {
    // Keywords
    TK_MODULE, TK_IMPORT, TK_EXPORT, TK_FROM, TK_AS,
    TK_FN, TK_LET, TK_CONST, TK_VAR, TK_MUT,
    TK_IF, TK_ELSE, TK_ELIF, TK_UNLESS, TK_WHEN,
    TK_FOR, TK_IN, TK_WHILE, TK_DO, TK_REPEAT, TK_UNTIL,
    TK_MATCH, TK_CASE, TK_DEFAULT, TK_WHERE,
    TK_TRY, TK_CATCH, TK_FINALLY, TK_THROW,
    TK_RETURN, TK_YIELD, TK_BREAK, TK_CONTINUE, TK_SKIP,
    TK_TRUE, TK_FALSE, TK_NIL, TK_UNDEFINED,
    TK_CLASS, TK_STRUCT, TK_ENUM, TK_TRAIT, TK_INTERFACE,
    TK_EXTENDS, TK_IMPLEMENTS, TK_NEW, TK_DELETE,
    TK_PUBLIC, TK_PRIVATE, TK_PROTECTED, TK_STATIC,
    TK_ABSTRACT, TK_FINAL, TK_OVERRIDE,
    TK_ASYNC, TK_AWAIT, TK_ASYNC_AWAIT,
    TK_TYPEOF, TK_INSTANCEOF, TK_VOID,
    TK_NAMESPACE, TK_USING, TK_WITH,
    TK_DEFMACRO, TK_MACRO, TK_QUOTE, TK_UNQUOTE,
    TK_DECORATOR, TK_ANNOTATION,
    TK_ASSERT, TK_TEST, TK_SUITE, TK_BENCH,
    TK_DEBUGGER, TK_TRACER, TK_LOG,
    TK_SUPER, TK_THIS, TK_CONSTRUCTOR,
    
    // Types
    TK_INT_TYPE, TK_FLOAT_TYPE, TK_STRING_TYPE, TK_BOOL_TYPE,
    TK_CHAR_TYPE, TK_ARRAY_TYPE, TK_OBJECT_TYPE, TK_FUNC_TYPE,
    TK_ANY_TYPE, TK_VOID_TYPE, TK_NULLABLE_TYPE,
    
    // Literals
    TK_IDENTIFIER, TK_NUMBER, TK_STRING_LIT, TK_CHAR_LIT,
    TK_REGEX_LIT, TK_TEMPLATE_LIT,
    
    // Operators
    TK_PLUS, TK_MINUS, TK_STAR, TK_SLASH, TK_PERCENT,
    TK_PLUS_EQ, TK_MINUS_EQ, TK_STAR_EQ, TK_SLASH_EQ,
    TK_PLUS_PLUS, TK_MINUS_MINUS,
    TK_PLUS_EQ_EQ, TK_MINUS_EQ_EQ,
    TK_EQ, TK_EQEQ, TK_EQEQEQ, TK_BANGEQ, TK_BANGEQEQ,
    TK_LT, TK_GT, TK_LTEQ, TK_GTEQ,
    TK_LSHIFT, TK_RSHIFT, TK_URSHIFT,
    TK_AMPERSAND, TK_BAR, TK_CARET, TK_TILDE,
    TK_AMPERSAND_EQ, TK_BAR_EQ, TK_CARET_EQ,
    TK_LSHIFT_EQ, TK_RSHIFT_EQ, TK_URSHIFT_EQ,
    TK_AND, TK_OR, TK_NOT, TK_XOR,
    TK_QUESTION, TK_DOUBLE_QUESTION, TK_BANG, TK_DOUBLE_BANG,
    TK_DOT, TK_DOTDOT, TK_DOTDOTDOT,
    TK_COLON, TK_DOUBLE_COLON, TK_SEMICOLON, TK_COMMA,
    TK_ARROW, TK_FAT_ARROW, TK_DOUBLE_ARROW,
    TK_PIPE, TK_DOUBLE_PIPE, TK_PIPELINE,
    TK_AT, TK_HASH, TK_DOLLAR,
    
    // Grouping
    TK_LPAREN, TK_RPAREN, TK_LBRACKET, TK_RBRACKET,
    TK_LBRACE, TK_RBRACE, TK_LANGLE, TK_RANGLE,
    
    // Special
    TK_UNDERSCORE, TK_ELLIPSIS, TK_BACKTICK,
    TK_SHEBANG, TK_COMMENT, TK_MULTILINE_COMMENT,
    TK_EOF, TK_ERROR
} TokenType;

// ===== PARSER =====
typedef enum {
    NODE_PROGRAM, NODE_BLOCK, NODE_VAR_DECL, NODE_CONST_DECL,
    NODE_FUNCTION, NODE_CLASS, NODE_METHOD, NODE_CONSTRUCTOR,
    NODE_IF, NODE_ELIF, NODE_ELSE, NODE_UNLESS,
    NODE_FOR, NODE_FOR_IN, NODE_WHILE, NODE_DO_WHILE,
    NODE_MATCH, NODE_CASE, NODE_DEFAULT,
    NODE_TRY, NODE_CATCH, NODE_FINALLY, NODE_THROW,
    NODE_RETURN, NODE_YIELD, NODE_BREAK, NODE_CONTINUE,
    NODE_CALL, NODE_NEW, NODE_SUPER, NODE_THIS,
    NODE_ACCESS, NODE_INDEX, NODE_SLICE,
    NODE_BINARY, NODE_UNARY, NODE_TERNARY,
    NODE_ASSIGN, NODE_COMPOUND_ASSIGN,
    NODE_LITERAL, NODE_IDENTIFIER, NODE_TEMPLATE,
    NODE_ARRAY, NODE_OBJECT, NODE_PROPERTY,
    NODE_SPREAD, NODE_REST, NODE_DESTRUCTURING,
    NODE_LAMBDA, NODE_ARROW_FUNC,
    NODE_ASYNC, NODE_AWAIT,
    NODE_IMPORT, NODE_EXPORT, NODE_MODULE,
    NODE_TYPE_DECL, NODE_GENERIC, NODE_UNION_TYPE,
    NODE_DECORATOR, NODE_ANNOTATION,
    NODE_MACRO_DEF, NODE_MACRO_CALL,
    NODE_PATTERN, NODE_WILDCARD, NODE_BIND_PATTERN,
    NODE_ARRAY_PATTERN, NODE_OBJECT_PATTERN,
    NODE_GUARD, NODE_WHERE,
    NODE_PIPELINE, NODE_COMPOSITION,
    NODE_COMPREHENSION, NODE_GENERATOR,
    NODE_TEST, NODE_ASSERT, NODE_BENCH,
    NODE_DEBUG, NODE_TRACE,
    NODE_EXPR_STMT, NODE_LOOP_BODY, NODE_NULLABLE_TYPE,
    NODE_IMPLEMENTS, NODE_EXPR
} NodeType;

#endif
